global:
  scrape_interval:    60s # By default, scrape targets every 15 seconds. 
  external_labels:
    monitor: 'snapcaster-prometheus'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'price_api'
    scrape_interval: 24h # Override the global default
    static_configs:
      - targets: ['analytics.snapcaster.ca/price']
